create table public.team_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.foundation_students (
  id bigint generated by default as identity primary key,
  registration_number text not null unique,
  student_name text not null,
  father_husband_name text,
  date_of_birth date,
  address_1 text,
  address_2 text,
  address_3 text,
  city text,
  pin_code text,
  email text,
  mobile text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.intermediate_students (
  id bigint generated by default as identity primary key,
  registration_number text not null unique,
  student_name text not null,
  father_husband_name text,
  date_of_birth date,
  address_1 text,
  address_2 text,
  address_3 text,
  city text,
  pin_code text,
  email text,
  mobile text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index foundation_students_name_idx
  on public.foundation_students (student_name);
create index foundation_students_mobile_idx
  on public.foundation_students (mobile);

create index intermediate_students_name_idx
  on public.intermediate_students (student_name);
create index intermediate_students_mobile_idx
  on public.intermediate_students (mobile);

alter table public.team_profiles enable row level security;
alter table public.foundation_students enable row level security;
alter table public.intermediate_students enable row level security;

revoke all on table public.team_profiles from anon, authenticated;
revoke all on table public.foundation_students from anon, authenticated;
revoke all on table public.intermediate_students from anon, authenticated;


grant select, insert, update on table public.foundation_students to authenticated;
grant select, insert, update on table public.intermediate_students to authenticated;
grant select on table public.team_profiles to authenticated;

create policy "team_member_can_read_own_profile"
  on public.team_profiles for select to authenticated
  using (id = auth.uid());

create policy "active_team_can_read_foundation"
  on public.foundation_students for select to authenticated
  using (
    exists (
      select 1 from public.team_profiles tp
      where tp.id = auth.uid() and tp.active = true
    )
  );

create policy "active_team_can_insert_foundation"
  on public.foundation_students for insert to authenticated
  with check (
    exists (
      select 1 from public.team_profiles tp
      where tp.id = auth.uid() and tp.active = true
    )
  );

create policy "active_team_can_update_foundation"
  on public.foundation_students for update to authenticated
  using (
    exists (
      select 1 from public.team_profiles tp
      where tp.id = auth.uid() and tp.active = true
    )
  )
  with check (
    exists (
      select 1 from public.team_profiles tp
      where tp.id = auth.uid() and tp.active = true
    )
  );

create policy "active_team_can_read_intermediate"
  on public.intermediate_students for select to authenticated
  using (
    exists (
      select 1 from public.team_profiles tp
      where tp.id = auth.uid() and tp.active = true
    )
  );

create policy "active_team_can_insert_intermediate"
  on public.intermediate_students for insert to authenticated
  with check (
    exists (
      select 1 from public.team_profiles tp
      where tp.id = auth.uid() and tp.active = true
    )
  );

create policy "active_team_can_update_intermediate"
  on public.intermediate_students for update to authenticated
  using (
    exists (
      select 1 from public.team_profiles tp
      where tp.id = auth.uid() and tp.active = true
    )
  )
  with check (
    exists (
      select 1 from public.team_profiles tp
      where tp.id = auth.uid() and tp.active = true
    )
  );
