create table public.team_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.students (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('FND','INTER')),
  registration_number text not null,
  student_name text not null,
  father_husband_name text,
  date_of_birth date,
  address_1 text,
  address_2 text,
  address_3 text,
  city text,
  pin_code text,
  email text,
  mobile text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint students_source_registration_unique unique (source, registration_number)
);

create index students_name_idx on public.students (student_name);
create index students_registration_idx on public.students (registration_number);
create index students_mobile_idx on public.students (mobile);

alter table public.team_profiles enable row level security;
alter table public.students enable row level security;

revoke all on table public.team_profiles from anon, authenticated;
revoke all on table public.students from anon, authenticated;
